name: synthesis module
on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
permissions:
  contents: read
  actions: read
jobs:
  run:
    uses: kyuhank/cpue-actions-demo/.github/workflows/execute-stage.yml@6dab4e7442ef546aff9f8b5f6631e0ab6345e953
    with:
      stage: ${{ inputs.stage }}
      module: synthesis
